apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-app
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: https://github.com/AhmedmmAli/ms-deployment.git
    targetRevision: main
    path: "k8s-files"
  destination:
    name: in-cluster 
    namespace: default
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:    
    - Validate=false
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 5 
      backoff:
        duration: 2m
        factor: 2
        maxDuration: 3m