apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-app-hpa-cpu
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-app
  minReplicas: 4
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75